# Generated by Django 3.2.6 on 2021-09-01 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('keywords', models.TextField(max_length=400)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
