# Generated by Django 3.2.6 on 2021-09-06 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20210901_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Overview',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Tagline',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='movie',
            name='Vote_average',
            field=models.DecimalField(decimal_places=3, default='0.0', max_digits=5),
        ),
    ]
